### PR TITLE
Set all release parameters for  OpenPegasus 2.14.3 release

### PR DESCRIPTION
**Pull request by KSchopmeyer**
This changes internal status flags to Released in the changes.rst and modifies one message to show released.  It does not change the Version status flag beause we did not set to development when we started 2.14.3

This PR has now passed the test suite.

This pr will be assumed passed if no comments are received by 14:00  Monday 13 June 2022

### CODE REVIEW

**Comment by cjrood** [comment]
LGTM! For this release, ship it! Next release I hope we can improve the MOF setup so there is less manual editing, and support for more recent windows compilers, cimple logging to syslog are my votes.

**Comment by KSchopmeyer** [comment]
Chris accidently closed the PR.  Open I again

**Comment by KSchopmeyer** [comment]
Comments from P. Lamana:

# README.md

 

## OpenPegasus Overview

 

FROM: WBEM server indication listener to receive async indications from a WBEM server

TO: WBEM server indication listener, a WBEM Client, to receive async indications from a WBEM server. 

FROM : WBEM Server CIM repository in which CIM classes and instances are stored

TO: WBEM Server CIM repository in which CIM classes and instances are stored and persisted. 

FROM: A number of DMTF Schemas specifically tuned to be built into OpenPegasus

TO: Common DMTF Profiles, schemas, specifically tuned for and built into OpenPegasus. 

FROM: A test suite for all of the components of OpenPegasus for unit and system tests.

TO: Both unit and system tests for all components of OpenPegasus. 

FROM: Documentation for OpenPegasus.

TO: Project documentation. 

FROM: A WEB interface for viewing the status of a running OpenPegasus server and managing runtime configuration.

TO: The http://server/webconfig WEB application for viewing the status of a running OpenPegasus server and managing its runtime configuration. 

FROM: Command line tools for inspecting and executing requests on a running server (cimcli)

TO: A command line CIM Client (cimcli) for executing CIM operation against a running WBEM server.

 

 ## OpenPegasus Availability:

FROM: Note that this github repository is OpenPegasus root directory is OpenPegasus and that directory includes the pegasus directory (source code, support code, documentation, CIM Schemas, etc.) which was the root directory in CVS) and a new docs directory where over time new documentation will be acccumulated.

TO: ?

 
## Limitations:

FROM: It is not tested against the full set of platforms for which OpenPegasus was designed and for which the releases up to 2.14 were tested. This is because the original test strategy was for each of the OpenPegasus teams to test OpenPegasus on their own platforms (IBM AIX, HPUX, etc.). The current developers of the github repository do not have access to these platforms so we cannot run these tests. As of 2.14.2 tests are run against Linux and Windows platforms.

 

TO: Releases past 2.14.1 have not been tested against the full set of platforms for which OpenPegasus was designed.  Previously releases were tested by the individual OpenPegasus teams on their own platforms (IBM AIX, HPUX, etc.). The current development teams no longer have access to these platforms. As of 2.14.2 tests are only run against the Linux and Windows platforms.
 
# Building, Testing, and Running OpenPegasus

 

## Setting OpenPegasus Build Configuration

FROM: OpenPegasus configuration is based entirely on environment variables to define the location of the source code, the build output directory, the compile characteristics, and the OpenPegasus configuration options In general all OpenPegasus configuration environment variables start with 'PEGASUS_'.

 TO: The OpenPegasus build is configurable through a set environment variables.  These variables define:

- Build type; debug, retail
- Location of the source code
- Build output directory
- Compile characteristics
- OpenPegasus configuration options???? 

In general, all OpenPegasus environment variables start with 'PEGASUS_'.

FROM: There are three environment variables that are absolutely required to compile OpenPegaus

PEGASUS_PLATFORM Defines the platform for which OpenPegasus is being compiled.

PEGASUS_ROOT - Defines the 'pegasus' directory the top of the OpenPegasus source tree. This directory contains the basic build Makefile for OpenPegasus and the subdirectories define the OpenPegasus components (ex. Pegasus, Clients, etc.)

PEGASUS_HOME - Target directory for compile output.

TO:

 PEGASUS_PLATFORM - Defines the platform for which OpenPegasus is being compiled. {What are the possible values}

PEGASUS_ROOT - Defines the top folder in the build directory.  This is the 'pegasus' directory cloned from the OpenPegasus repository. This directory contains the basic build Makefile and its subdirectories contain the OpenPegasus components (ex. Pegasus, Clients, etc.)

PEGASUS_HOME - Target directory for compile output.  If this folder does not exist, it will be created.  This folder is typically called build_output and placed at the same level as the 'pegasus' folder so as to separate build products from the source code.

 

 

OpenPegasus Build and Test

 

FROM: The simplest make is make world which does a complete build of OpenPegasus and the test tools, builds a run environment and runs the full test suite.

 

TO: The simplest make is make world which does a complete retail build of OpenPegasus, test tools, runtime environment and executes the full test suite.

 

 

Running OpenPegasus

 

You don't say anything about the environment path being updated for running the cimserver.

 

Also nothing about container and executing from a Docker container.

**Comment by KSchopmeyer** [comment]
Comments from Peter incorporated (see the comment above for list and my comments), found one extra file in OpenPegasus/docs that I deleted, and fixed some mispellings in the doc.  Updated the sample setup.sh to add more comments on why it exists and what each statement means.

**Pull request merged**
